version: "3.8"

services:
    web:
        build: ./flask_app
        ports:
            - "5000:5000"
        environment:
            - REDIS_URL=redis://redis:6379
            - DATABASE_URL=mysql://flaskapp:password@mysql/flaskdb  
        depends_on:
            - redis
            - mysql 
        networks:
            - mynetwork

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        networks:
            - mynetwork

    mysql:
        image: "mysql:5.7" 
        environment:
            MYSQL_ROOT_PASSWORD: cloudcomputing 
            MYSQL_DATABASE: cloud
            MYSQL_USER: EddyKubwimana 
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"  
        volumes:
            - mysql-data:/var/lib/mysql  
        networks:
            - mynetwork

volumes:
    mysql-data:  

networks:
    mynetwork:
        driver: bridge
